feat: use default branch provided by GitHub

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -70,7 +70,12 @@ jobs:
       - name: Get Deployment URL
         id: deployment-url
         run: |
-          SUBDOMAIN=$([[ $GITHUB_REF = "refs/heads/master" || $GITHUB_REF = "refs/heads/main" ]] && echo "" || echo "preview-${{ inputs.tree_hash }}.")
+          DEFAULT_BRANCH=${{ github.event.repository.default_branch }}
+          if [[ -z "$DEFAULT_BRANCH" ]]; then
+              echo "Could not determine default branch"
+              exit 1
+          fi
+          SUBDOMAIN=$([[ $GITHUB_REF = "refs/heads/$DEFAULT_BRANCH" ]] && echo "" || echo "preview-${{ inputs.tree_hash }}.")
           echo "::set-output name=url::https://${SUBDOMAIN}${{ inputs.domain_name }}"
 
       - name: Setup AWS Credentials for Registry Bucket Access
