chore!: update actions in spa-tools to versions using node 20 (#213)

diff --git a/reusable-workflows/deploy.yml b/reusable-workflows/deploy.yml
--- a/reusable-workflows/deploy.yml
+++ b/reusable-workflows/deploy.yml
@@ -58,7 +58,7 @@ jobs:
     outputs:
       deployment_url: ${{ steps.deployment-url.outputs.url }}
     steps:
-      - uses: actions/checkout@v3.5.2
+      - uses: actions/checkout@v4.1.4
       - uses: actions/setup-node@v3.6.0
         with:
           node-version: "20"
@@ -79,11 +79,10 @@ jobs:
           echo "url=https://${SUBDOMAIN}${{ inputs.domain_name }}" >> $GITHUB_OUTPUT
 
       - name: Setup AWS Credentials for Registry Bucket Access
-        uses: aws-actions/configure-aws-credentials@v2.0.0
+        uses: aws-actions/configure-aws-credentials@v4.0.2
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_FRONTEND_REGISTRY }}
-          aws-secret-access-key:
-            ${{ secrets.AWS_SECRET_ACCESS_KEY_FRONTEND_REGISTRY }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_FRONTEND_REGISTRY }}
           aws-region: eu-west-1
 
       - name: Download & Unpack Bundle
@@ -92,7 +91,7 @@ jobs:
           mkdir ${{ inputs.bundle_dir }} && tar -xvzf bundle.tar.gz -C ${{ inputs.bundle_dir }}
 
       - name: Setup AWS Credentials for Origin Bucket Access
-        uses: aws-actions/configure-aws-credentials@v2.0.0
+        uses: aws-actions/configure-aws-credentials@v4.0.2
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -122,12 +121,12 @@ jobs:
 
       - name: Update .well-known Files If Exists
         run: |
-           aws s3 cp \
-            s3://${{ inputs.bucket_name }}/html/${{ inputs.tree_hash }}/.well-known/apple-app-site-association \
-            s3://${{ inputs.bucket_name }}/html/${{ inputs.tree_hash }}/.well-known/apple-app-site-association \
-            --content-type 'application/json' \
-            --cache-control 'public,max-age=3600' \
-            --metadata-directive REPLACE || echo "Failed updating .well-known files"
+          aws s3 cp \
+           s3://${{ inputs.bucket_name }}/html/${{ inputs.tree_hash }}/.well-known/apple-app-site-association \
+           s3://${{ inputs.bucket_name }}/html/${{ inputs.tree_hash }}/.well-known/apple-app-site-association \
+           --content-type 'application/json' \
+           --cache-control 'public,max-age=3600' \
+           --metadata-directive REPLACE || echo "Failed updating .well-known files"
 
       - name: Update Cursor File
         id: cursor-update
@@ -147,7 +146,7 @@ jobs:
             ]
 
       - name: Upload Deployed Bundle as Artifact
-        uses: actions/upload-artifact@v3.1.2
+        uses: actions/upload-artifact@v4.3.3
         with:
           name: bundle-${{ inputs.tree_hash }}-${{ inputs.environment }}
           path: bundle.tar.gz
